// Generates content/page-scripts.js from the worker's own page scripts, so the
// extension reads application forms exactly the way the worker does. Run
// `pnpm --filter @autoapply/extension build` after changing
// packages/ats-adapters/src/form/dom-scripts.ts; a test fails if you forget.
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pageScriptsSource } from "@autoapply/ats-adapters";

export const PAGE_SCRIPTS_PATH = resolve(import.meta.dirname, "../content/page-scripts.js");

export function pageScriptsFile(): string {
  return `// Generated by apps/extension/scripts/build.ts from packages/ats-adapters/src/form/dom-scripts.ts. Do not edit.
// Read-only page scans shared with the Applyance worker: form fields, security checks, confirmations.
globalThis.__applyancePage = ${pageScriptsSource()};
`;
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(import.meta.filename)) {
  writeFileSync(PAGE_SCRIPTS_PATH, pageScriptsFile());
  process.stdout.write(`Wrote ${PAGE_SCRIPTS_PATH}\n`);
}
