import type { Locator, Page } from "playwright-core";
import { AutomationError, assignFieldKeys, classifyFailure, orderLocators, type DetectedField, type FieldKind, type FieldLocator, type FieldMapping } from "@autoapply/automation";
import type { AdapterContext, AdapterStatus, ApplicationAdapter, DocumentsToUpload, PageAdvance, ValidationResult } from "../adapter";
import { BUTTONS_SCRIPT, CONFIRMATION_SCRIPT, NATIVE_VALIDITY_SCRIPT, SCAN_FIELDS_SCRIPT, SECURITY_SCRIPT, VALIDATION_SCRIPT } from "./dom-scripts";

interface ScannedField {
  kind: string;
  label: string;
  labelVia: "label" | "aria" | "dom" | "none";
  required: boolean;
  options?: string[];
  optionValues?: string[];
  multiple: boolean;
  name: string;
  id: string;
  placeholder: string;
  autocomplete: string;
  inputType: string;
  accept: string;
  ariaLabel: string;
  domPath: string;
}

interface ScannedButton {
  text: string;
  type: string;
  inForm: boolean;
  domPath: string;
}

const NEXT = /^(next|continue|save (and|&) continue|next step|next page|proceed)\b/i;
const SUBMIT = /^(submit|submit application|send application|apply|apply now|finish|complete( application)?|send)\b/i;
const START = /^(apply|apply now|apply for this (job|position|role)|start (your )?application|i'?m interested)\b/i;

/** Ids generated by frameworks change between page loads, so they aren't used as locators. */
const UNSTABLE_ID = /\d{4,}|^[:_]|[a-f0-9]{10,}|^(react|ember|mui|radix|headlessui)[-_:]/i;

const cssString = (s: string) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

function kindOf(f: ScannedField): FieldKind {
  switch (f.kind) {
    case "textarea": return "textarea";
    case "select": return "select";
    case "radio": return "radio";
    case "checkbox": return "checkbox";
    case "file": return "file";
    case "email": return "email";
    case "tel": return "phone";
    case "url": return "url";
    case "number": return "number";
    case "date": return "date";
    case "text": case "": return "text";
    default: return "text";
  }
}

/** Candidate locators in the preferred order: label, name, stable id, ARIA, DOM path. Never coordinates. */
function locatorsFor(f: ScannedField): FieldLocator[] {
  const out: FieldLocator[] = [];
  if (f.label && f.labelVia === "label" && f.kind !== "radio" && !(f.kind === "checkbox" && f.multiple)) out.push({ strategy: "label", value: f.label });
  if (f.name) out.push({ strategy: "name", value: f.name });
  if (f.id && !UNSTABLE_ID.test(f.id)) out.push({ strategy: "id", value: f.id });
  if (f.ariaLabel) out.push({ strategy: "aria", value: f.ariaLabel });
  if (f.domPath) out.push({ strategy: "dom", value: f.domPath });
  return orderLocators(out);
}

const tagFor = (kind: FieldKind) => (kind === "select" ? "select" : kind === "textarea" ? "textarea" : "input");

/**
 * Works on any HTML application form: finds fields by their labels, fills them
 * from resolved mappings, handles dropdowns, radios, checkboxes, uploads and
 * multi-page flows, and reports CAPTCHAs and sign-in walls instead of touching them.
 */
export class GenericWebFormAdapter implements ApplicationAdapter<Page> {
  readonly platform = "GENERIC" as const;
  readonly displayName = "Generic web form";
  readonly supportsAutoSubmit = true;

  detect(): number {
    return 10;
  }

  async initialize(ctx: AdapterContext<Page>): Promise<void> {
    const { page } = ctx;
    await page.waitForLoadState("domcontentloaded");
    await page.waitForLoadState("networkidle", { timeout: 5000 }).catch(() => undefined);
    if ((await this.scan(page)).length > 0) return;
    // A job description page: follow its Apply button or link once.
    const start = page.getByRole("link", { name: START }).or(page.getByRole("button", { name: START })).first();
    if (await start.count()) {
      await ctx.log({ type: "NOTE", message: "Opened the application form from the job page" });
      await Promise.all([page.waitForLoadState("domcontentloaded").catch(() => undefined), start.click()]);
      await page.waitForLoadState("networkidle", { timeout: 5000 }).catch(() => undefined);
    }
  }

  async mapFields(ctx: AdapterContext<Page>): Promise<{ fields: DetectedField[]; mappings: FieldMapping[] }> {
    const scanned = await this.scan(ctx.page);
    const fields = assignFieldKeys(
      scanned.map((f) => ({
        label: f.label || f.name || "Unlabeled field",
        kind: kindOf(f),
        required: f.required,
        options: f.options,
        optionValues: f.optionValues,
        multiple: f.multiple,
        pageIndex: ctx.pageIndex,
        locators: locatorsFor(f),
        hints: { name: f.name || undefined, id: f.id || undefined, placeholder: f.placeholder || undefined, autocomplete: f.autocomplete || undefined, inputType: f.inputType, accept: f.accept || undefined },
      })),
    );
    const mappings: FieldMapping[] = [];
    for (const field of fields) mappings.push(await ctx.resolveField(field));
    return { fields, mappings };
  }

  async fillFields(ctx: AdapterContext<Page>, mappings: FieldMapping[]): Promise<void> {
    for (const m of mappings) {
      if (m.mappedField.startsWith("documents.") || m.mappedField === "answer.library" || m.mappedField === "unknown") continue;
      await this.fillOne(ctx, m);
    }
  }

  async answerQuestions(ctx: AdapterContext<Page>, mappings: FieldMapping[]): Promise<void> {
    for (const m of mappings) {
      if (m.mappedField !== "answer.library" && m.mappedField !== "unknown") continue;
      await this.fillOne(ctx, m);
    }
  }

  async uploadDocuments(ctx: AdapterContext<Page>, documents: DocumentsToUpload, mappings: FieldMapping[]): Promise<void> {
    for (const m of mappings) {
      if (m.field.kind !== "file" || m.status === "SKIPPED") continue;
      const doc = m.mappedField === "documents.resume" ? documents.resume : m.mappedField === "documents.coverLetter" ? documents.coverLetter : undefined;
      if (!doc) continue;
      ctx.signal.throwIfAborted();
      const locator = await this.locate(ctx.page, m.field);
      await locator.setInputFiles(doc.path);
      await ctx.log({ type: m.mappedField === "documents.resume" ? "RESUME_UPLOADED" : "COVER_LETTER_UPLOADED", message: `Uploaded ${doc.fileName} to "${m.detectedLabel}"` });
    }
  }

  async validate(ctx: AdapterContext<Page>): Promise<ValidationResult> {
    const native = (await ctx.page.evaluate(NATIVE_VALIDITY_SCRIPT)) as Array<{ label: string; message: string }>;
    const shown = (await ctx.page.evaluate(VALIDATION_SCRIPT)) as { errors: Array<{ label: string; message: string }>; alerts: string[] };
    const errors = [...native, ...shown.errors.filter((e) => !native.some((n) => n.label === e.label))];
    return { ok: errors.length === 0, errors };
  }

  async nextPage(ctx: AdapterContext<Page>): Promise<PageAdvance> {
    const button = await this.findButton(ctx.page, "next");
    if (!button) throw new AutomationError("SITE_CHANGED", "Couldn't find the button to the next page of the form");
    return this.clickAndWait(ctx, button);
  }

  async submit(ctx: AdapterContext<Page>): Promise<{ confirmation?: string } | { validation: ValidationResult }> {
    const button = await this.findButton(ctx.page, "submit");
    if (!button) throw new AutomationError("SITE_CHANGED", "Couldn't find the form's submit button");
    const result = await this.clickAndWait(ctx, button);
    const status = await this.getStatus(ctx);
    if (status.state === "submitted") return { confirmation: status.confirmation };
    if (!result.moved) return { validation: result.validation };
    if (status.state === "needs_human") throw new AutomationError(status.reason === "CAPTCHA" ? "CAPTCHA" : "AUTH_REQUIRED", status.detail);
    const validation = await this.validate(ctx);
    if (!validation.ok) return { validation };
    throw new AutomationError("SITE_CHANGED", "The form was sent but no confirmation appeared");
  }

  async getStatus(ctx: AdapterContext<Page>): Promise<AdapterStatus> {
    const { page } = ctx;
    const security = (await page.evaluate(SECURITY_SCRIPT)) as { captcha: boolean; mfa: boolean; login: boolean; signInText: boolean };
    if (security.captcha) return { state: "needs_human", reason: "CAPTCHA", detail: "This site is asking for a CAPTCHA. AutoApply never solves CAPTCHAs." };
    if (security.mfa) return { state: "needs_human", reason: "MFA", detail: "This site is asking for a verification code. AutoApply never handles sign-in codes." };
    if (security.login) return { state: "needs_human", reason: "AUTH_REQUIRED", detail: "This site requires you to sign in or create an account. AutoApply never enters passwords." };
    const confirmation = (await page.evaluate(CONFIRMATION_SCRIPT)) as { confirmed: boolean; confirmation: string | null };
    const fields = await this.scan(page);
    if (confirmation.confirmed && fields.length === 0) return { state: "submitted", confirmation: confirmation.confirmation ?? undefined };
    const next = await this.findButton(page, "next");
    const submit = await this.findButton(page, "submit");
    return { state: "in_progress", page: ctx.pageIndex, isFinalPage: !next && !!submit, hasForm: fields.length > 0 };
  }

  async handleFailure(_ctx: AdapterContext<Page>, error: unknown): Promise<AdapterStatus> {
    const failure = classifyFailure(error);
    return { state: "failed", failure, message: error instanceof Error ? error.message.split("\n")[0]!.slice(0, 500) : String(error) };
  }

  // ─── internals ────────────────────────────────────────────────────────────

  private async scan(page: Page): Promise<ScannedField[]> {
    return (await page.evaluate(SCAN_FIELDS_SCRIPT)) as ScannedField[];
  }

  /** Resolve a field to exactly one element, trying locator strategies in priority order. */
  private async locate(page: Page, field: DetectedField): Promise<Locator> {
    const tag = tagFor(field.kind);
    for (const loc of field.locators) {
      let candidate: Locator;
      switch (loc.strategy) {
        case "label": candidate = page.getByLabel(loc.value, { exact: true }); break;
        case "name": candidate = page.locator(`${tag}[name=${cssString(loc.value)}]`); break;
        case "id": candidate = page.locator(`#${cssEscapeId(loc.value)}`); break;
        case "aria": candidate = page.locator(`[aria-label=${cssString(loc.value)}]`); break;
        case "dom": candidate = page.locator(loc.value); break;
      }
      if ((await candidate.count()) === 1) return candidate;
    }
    throw new AutomationError("SELECTOR_ERROR", `Couldn't find the "${field.label}" field on the page`);
  }

  /** The inputs of a radio or checkbox group, located by name, falling back to the DOM path. */
  private groupInputs(page: Page, field: DetectedField): Locator {
    const type = field.kind === "radio" ? "radio" : "checkbox";
    const name = field.hints?.name;
    if (name) return page.locator(`input[type="${type}"][name=${cssString(name)}]`);
    const dom = field.locators.find((l) => l.strategy === "dom");
    if (dom) return page.locator(dom.value);
    throw new AutomationError("SELECTOR_ERROR", `Couldn't find the "${field.label}" choices`);
  }

  private async pickInGroup(page: Page, field: DetectedField, wanted: string[], exclusive: boolean) {
    const type = field.kind === "radio" ? "radio" : "checkbox";
    const inputs = this.groupInputs(page, field);
    const options = field.options ?? [];
    const targets: Locator[] = [];
    for (const option of wanted) {
      const byLabel = inputs.and(page.getByRole(type, { name: option, exact: true }));
      if ((await byLabel.count()) === 1) {
        targets.push(byLabel);
        continue;
      }
      const value = field.optionValues?.[options.indexOf(option)];
      const byValue = value ? inputs.and(page.locator(`[value=${cssString(value)}]`)) : null;
      if (byValue && (await byValue.count()) === 1) targets.push(byValue);
      else throw new AutomationError("SELECTOR_ERROR", `Couldn't select "${option}" for "${field.label}"`);
    }
    if (!exclusive) {
      // Start from a clean group so the ticked boxes match the answer exactly.
      const count = await inputs.count();
      for (let i = 0; i < count; i++) if (await inputs.nth(i).isChecked()) await inputs.nth(i).uncheck();
    }
    for (const t of targets) await t.check();
  }

  private async fillOne(ctx: AdapterContext<Page>, m: FieldMapping): Promise<void> {
    if (m.value == null || m.status === "SKIPPED" || (m.status === "NEEDS_REVIEW" && m.source === "none")) return;
    ctx.signal.throwIfAborted();
    const { page } = ctx;
    const field = m.field;
    switch (field.kind) {
      case "radio":
        await this.pickInGroup(page, field, [String(m.value)], true);
        return;
      case "checkbox":
        if (field.multiple) {
          await this.pickInGroup(page, field, Array.isArray(m.value) ? m.value : [m.value], false);
        } else {
          const locator = await this.locate(page, field);
          await locator.setChecked(m.value === "Yes");
        }
        return;
      case "select": {
        const locator = await this.locate(page, field);
        await locator.selectOption({ label: String(m.value) });
        return;
      }
      case "file":
        return;
      default: {
        const locator = await this.locate(page, field);
        const value = Array.isArray(m.value) ? m.value.join(", ") : m.value;
        await locator.fill(value);
        // Some sites reformat or reject input; read it back so a silent mismatch is caught by validation.
        const actual = await locator.inputValue();
        if (actual.replace(/\D/g, "") !== value.replace(/\D/g, "") && actual.trim() !== value.trim() && field.kind !== "date") {
          await ctx.log({ type: "NOTE", level: "WARNING", message: `"${field.label}" shows "${actual.slice(0, 80)}" after filling` });
        }
      }
    }
  }

  private async findButton(page: Page, kind: "next" | "submit"): Promise<Locator | null> {
    const buttons = (await page.evaluate(BUTTONS_SCRIPT)) as ScannedButton[];
    const pattern = kind === "next" ? NEXT : SUBMIT;
    let match = buttons.find((b) => pattern.test(b.text));
    if (!match && kind === "submit" && !buttons.some((b) => NEXT.test(b.text))) {
      // A form with a single unlabeled submit button.
      const formSubmits = buttons.filter((b) => b.inForm && b.type === "submit");
      if (formSubmits.length === 1) match = formSubmits[0];
    }
    if (!match) return null;
    const byRole = page.getByRole("button", { name: match.text, exact: true });
    if (match.text && (await byRole.count()) === 1) return byRole;
    const byPath = page.locator(match.domPath);
    return (await byPath.count()) === 1 ? byPath : null;
  }

  /** Click a navigation button and wait for either a new page or visible validation errors. */
  private async clickAndWait(ctx: AdapterContext<Page>, button: Locator): Promise<PageAdvance> {
    const { page } = ctx;
    ctx.signal.throwIfAborted();
    const before = { url: page.url(), fields: JSON.stringify((await this.scan(page)).map((f) => f.name + f.label)) };
    const navigation = page.waitForNavigation({ timeout: 15_000, waitUntil: "domcontentloaded" }).then(() => true).catch(() => false);
    await button.click();
    const navigated = await Promise.race([navigation, page.waitForTimeout(2500).then(() => false)]);
    if (!navigated) await page.waitForLoadState("domcontentloaded").catch(() => undefined);
    await page.waitForLoadState("networkidle", { timeout: 5000 }).catch(() => undefined);
    const after = { url: page.url(), fields: JSON.stringify((await this.scan(page)).map((f) => f.name + f.label)) };
    if (after.url !== before.url || after.fields !== before.fields) {
      const validation = await this.validate(ctx);
      // Same page re-rendered with errors (server-side validation).
      if (after.url === before.url && !validation.ok) return { moved: false, validation };
      return { moved: true };
    }
    const validation = await this.validate(ctx);
    if (validation.ok) {
      const shown = (await page.evaluate(VALIDATION_SCRIPT)) as { alerts: string[] };
      return { moved: false, validation: { ok: false, errors: shown.alerts.length ? shown.alerts.map((a) => ({ label: "Form", message: a })) : [{ label: "Form", message: "The page didn't change after clicking the button" }] } };
    }
    return { moved: false, validation };
  }
}

function cssEscapeId(id: string): string {
  return id.replace(/([^a-zA-Z0-9_-])/g, "\\$1");
}
