import { AlignmentType, BorderStyle, Document, Packer, Paragraph, TabStopType, TextRun } from "docx";
import type { CoverLetterContent, ResumeContent } from "@autoapply/shared";

/** Word versions of generated resumes and cover letters, editable and ATS-friendly (no tables or text boxes). */

const FONT = "Calibri";
const MUTED = "5C5C66";
/** Right edge of the text area for 1-inch margins on Letter paper, in twentieths of a point. */
const RIGHT_TAB = 9360;

function headerParagraphs(h: ResumeContent["header"]): Paragraph[] {
  const out = [new Paragraph({ children: [new TextRun({ text: h.name, bold: true, size: 40 })], spacing: { after: 40 } })];
  if (h.headline) out.push(new Paragraph({ children: [new TextRun({ text: h.headline, size: 23, color: MUTED })], spacing: { after: 40 } }));
  if (h.contact.length) out.push(new Paragraph({ children: [new TextRun({ text: h.contact.join("  ·  "), size: 19, color: MUTED })], spacing: { after: 120 } }));
  return out;
}

const heading = (text: string) =>
  new Paragraph({
    children: [new TextRun({ text: text.toUpperCase(), bold: true, size: 20 })],
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "999999", space: 2 } },
    spacing: { before: 200, after: 80 },
  });

const body = (text: string, options: { size?: number; color?: string; italics?: boolean; after?: number } = {}) =>
  new Paragraph({ children: [new TextRun({ text, size: options.size ?? 21, color: options.color, italics: options.italics })], spacing: { after: options.after ?? 60 } });

const bullet = (text: string, size = 21) => new Paragraph({ children: [new TextRun({ text, size })], bullet: { level: 0 }, spacing: { after: 40 } });

const split = (left: string, right: string) =>
  new Paragraph({
    tabStops: [{ type: TabStopType.RIGHT, position: RIGHT_TAB }],
    children: [new TextRun({ text: left, bold: true, size: 21 }), ...(right ? [new TextRun({ text: `\t${right}`, size: 19, color: MUTED })] : [])],
    spacing: { before: 80, after: 20 },
  });

function pack(title: string, creator: string, children: Paragraph[]) {
  const doc = new Document({
    title,
    creator,
    description: "Generated by Applyance from the Master Profile",
    styles: { default: { document: { run: { font: FONT, size: 21 } } } },
    sections: [{ properties: { page: { margin: { top: 1080, bottom: 1080, left: 1440, right: 1440 } } }, children }],
  });
  return Packer.toBuffer(doc);
}

export async function renderResumeDocx(content: ResumeContent): Promise<Buffer> {
  const children = headerParagraphs(content.header);
  if (content.summary) children.push(heading("Summary"), body(content.summary));
  if (content.skills.length) children.push(heading("Skills"), body(content.skills.join(", ")));
  if (content.experience.length) {
    children.push(heading("Experience"));
    for (const role of content.experience) {
      children.push(split(`${role.title}, ${role.company}`, role.dates));
      if (role.location) children.push(body(role.location, { size: 19, color: MUTED, italics: true, after: 40 }));
      for (const b of role.bullets) children.push(bullet(b));
    }
  }
  if (content.education.length) {
    children.push(heading("Education"));
    for (const ed of content.education) {
      children.push(split(ed.school, ed.dates ?? ""));
      if (ed.credential) children.push(body(ed.credential, { after: 20 }));
      for (const d of ed.details) children.push(body(d, { size: 19, color: MUTED, after: 20 }));
    }
  }
  return pack(`${content.header.name} – Resume – ${content.job.company}`, content.header.name, children);
}

export async function renderCoverLetterDocx(content: CoverLetterContent, date = new Date()): Promise<Buffer> {
  const children = headerParagraphs(content.header);
  children.push(new Paragraph({ children: [new TextRun({ text: date.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }), size: 22 })], spacing: { before: 240, after: 240 }, alignment: AlignmentType.LEFT }));
  for (const p of content.paragraphs) children.push(p.startsWith("• ") ? bullet(p.slice(2), 22) : body(p, { size: 22, after: 160 }));
  return pack(`${content.header.name} – Cover letter – ${content.job.company}`, content.header.name, children);
}
