import type { Locator, Page } from "playwright-core";
import { AutomationError, assignFieldKeys, chooseOption, classifyFailure, displayLabel, orderLocators, type DetectedField, type FieldHints, type FieldKind, type FieldLocator, type FieldMapping } from "@autoapply/automation";
import type { Platform } from "@autoapply/shared";
import type { AdapterContext, AdapterStatus, ApplicationAdapter, DocumentsToUpload, HumanStep, PageAdvance, ValidationResult } from "../adapter";
import { buttonsScript, CONFIRMATION_SCRIPT, NATIVE_VALIDITY_SCRIPT, OPEN_OPTIONS_SCRIPT, scanFieldsScript, SECURITY_SCRIPT, VALIDATION_SCRIPT, type ScanOptions } from "./dom-scripts";

/** A field as the page scan reports it (see scanFieldsScript). */
export interface ScannedField {
  kind: string;
  widget: NonNullable<FieldHints["widget"]>;
  label: string;
  labelVia: "label" | "aria" | "dom" | "none";
  required: boolean;
  options?: string[];
  optionValues?: string[];
  multiple: boolean;
  name: string;
  id: string;
  placeholder: string;
  autocomplete: string;
  inputType: string;
  accept: string;
  ariaLabel: string;
  domPath: string;
}

interface ScannedButton {
  text: string;
  type: string;
  inForm: boolean;
  domPath: string;
}

/**
 * What makes one ATS different from another, as data. The shared form engine
 * below does the work; each platform adapter only describes its site.
 */
export interface FormAdapterOptions {
  platform: Platform;
  displayName: string;
  /** Whether Auto mode may submit on this platform (every other safety check still applies). */
  supportsAutoSubmit: boolean;
  scan?: ScanOptions;
  /**
   * Buttons that lead from a job page to the form, tried in order and
   * repeatedly (Workday: Apply, then Apply Manually). Never sign-in buttons.
   */
  startButtons?: string[];
  /** The site's own navigation buttons; each is classified as next or submit by its text. */
  navigationButtons?: string[];
  /** Ids this platform generates that are nevertheless stable (e.g. Ashby's `_systemfield_name`). */
  stableIds?: RegExp;
  /** Platform-specific explanation when a person has to step in. */
  humanDetail?: Partial<Record<HumanStep, string>>;
  /** How long to wait after a resume upload for the site to finish reading it (some sites refill fields from it). */
  uploadSettleMs?: number;
}

/** How long a single-page app may take to render its Apply button or form. */
const SPA_RENDER_MS = 15_000;

const NEXT = /^(next|continue|save (and|&) continue|next step|next page|proceed)\b/i;
const SUBMIT = /^(submit|submit application|send application|apply|apply now|finish|complete( application)?|send)\b/i;
const START = /^(apply|apply now|apply for this (job|position|role)|start (your )?application|i'?m interested|apply manually)\b/i;
/** Buttons AutoApply never presses: third-party sign-in and account creation. */
const NEVER_PRESS = /\b(with|via|using) (linkedin|indeed|google|facebook|seek|xing|apple|github|microsoft)\b|\bsign ?in\b|\blog ?in\b|create (an )?account|autofill with resume|use my last application/i;

/** Ids generated by frameworks change between page loads, so they aren't used as locators. */
const UNSTABLE_ID = /\d{4,}|^[:_]|[a-f0-9]{10,}|^(react|ember|mui|radix|headlessui)[-_:]|^input-\d+$/i;

const DEFAULT_HUMAN_DETAIL: Record<HumanStep, string> = {
  CAPTCHA: "This site is asking for a CAPTCHA. AutoApply never solves CAPTCHAs.",
  MFA: "This site is asking for a verification code. AutoApply never handles sign-in codes.",
  AUTH_REQUIRED: "This site requires you to sign in or create an account. AutoApply never enters passwords.",
};

const cssString = (s: string) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
const clean = (s: string) => s.replace(/\s+/g, " ").trim();

function kindOf(f: ScannedField): FieldKind {
  switch (f.kind) {
    case "textarea": return "textarea";
    case "select": return "select";
    case "radio": return "radio";
    case "checkbox": return "checkbox";
    case "file": return "file";
    case "email": return "email";
    case "tel": return "phone";
    case "url": return "url";
    case "number": return "number";
    case "date": return "date";
    default: return "text";
  }
}

/** Candidate locators in the preferred order: label, name, stable id, ARIA, DOM path. Never coordinates. */
function locatorsFor(f: ScannedField, stableIds?: RegExp): FieldLocator[] {
  const out: FieldLocator[] = [];
  const grouped = f.kind === "radio" || (f.kind === "checkbox" && f.multiple);
  if (f.label && f.labelVia === "label" && !grouped) out.push({ strategy: "label", value: f.label });
  if (f.name) out.push({ strategy: "name", value: f.name });
  const stable = stableIds?.test(f.id) || !UNSTABLE_ID.test(f.id);
  if (f.id && stable) out.push({ strategy: "id", value: f.id });
  if (f.ariaLabel) out.push({ strategy: "aria", value: f.ariaLabel });
  if (f.domPath) out.push({ strategy: "dom", value: f.domPath });
  return orderLocators(out);
}

/** Scanned fields as DetectedFields with stable keys, the input to field resolution. */
export function toDetectedFields(scanned: ScannedField[], pageIndex: number, stableIds?: RegExp): DetectedField[] {
  return assignFieldKeys(
    scanned.map((f) => ({
      label: f.label || f.name || "Unlabeled field",
      kind: kindOf(f),
      required: f.required,
      options: f.options,
      optionValues: f.optionValues,
      multiple: f.multiple,
      pageIndex,
      locators: locatorsFor(f, stableIds),
      hints: { name: f.name || undefined, id: f.id || undefined, placeholder: f.placeholder || undefined, autocomplete: f.autocomplete || undefined, inputType: f.inputType, accept: f.accept || undefined, widget: f.widget },
    })),
  );
}

const tagFor = (field: DetectedField) => {
  if (field.hints?.widget === "listbox") return "button";
  return field.kind === "select" && field.hints?.widget !== "combobox" ? "select" : field.kind === "textarea" ? "textarea" : "input";
};

/**
 * Fills HTML application forms: finds fields by their labels, fills them from
 * resolved mappings, handles native and custom dropdowns, radios, answer
 * buttons, checkboxes, uploads and multi-page flows, and reports CAPTCHAs and
 * sign-in walls instead of touching them. Platform adapters configure it.
 */
export class FormAdapter implements ApplicationAdapter<Page> {
  readonly platform: Platform;
  readonly displayName: string;
  readonly supportsAutoSubmit: boolean;
  private readonly fieldsScript: string;
  private readonly navScript: string;

  constructor(protected readonly options: FormAdapterOptions) {
    this.platform = options.platform;
    this.displayName = options.displayName;
    this.supportsAutoSubmit = options.supportsAutoSubmit;
    this.fieldsScript = scanFieldsScript(options.scan);
    this.navScript = buttonsScript(options.scan);
  }

  /** How this platform's fields are scanned (also used by the browser extension). */
  get scanOptions(): ScanOptions {
    return this.options.scan ?? {};
  }

  detect(_url: string, _html?: string): number | Promise<number> {
    return 10;
  }

  async initialize(ctx: AdapterContext<Page>): Promise<void> {
    const { page } = ctx;
    await this.settle(page);
    const landmarks = [...(this.options.scan?.roots ?? []), ...(this.options.startButtons ?? [])];
    if (this.options.scan?.rootRequired && landmarks.length) {
      // Single-page apps (Workday) can still be blank once the network goes quiet; give the Apply button or the form time to render.
      await page.locator(landmarks.join(", ")).first().waitFor({ state: "visible", timeout: SPA_RENDER_MS }).catch(() => undefined);
    }
    // A job description page: follow its Apply buttons until the form (or a sign-in wall) shows.
    for (let step = 0; step < 3; step++) {
      if ((await this.scan(page)).length > 0) return;
      const security = await this.security(page);
      if (security.captcha || security.mfa || security.login) return;
      const start = await this.findStartButton(page);
      if (!start) return;
      const text = clean((await start.textContent().catch(() => "")) ?? "");
      await ctx.log({ type: "NOTE", message: `Opened the application form from the job page${text ? ` ("${text.slice(0, 40)}")` : ""}` });
      await Promise.all([page.waitForLoadState("domcontentloaded").catch(() => undefined), start.click()]);
      await this.settle(page);
    }
  }

  async mapFields(ctx: AdapterContext<Page>): Promise<{ fields: DetectedField[]; mappings: FieldMapping[] }> {
    const fields = toDetectedFields(await this.scan(ctx.page), ctx.pageIndex, this.options.stableIds);
    // Custom dropdowns only render their choices when opened; read them so values can be matched.
    for (const field of fields) {
      const widget = field.hints?.widget;
      if ((widget === "combobox" || widget === "listbox") && !field.options?.length) {
        const options = await this.readOptions(ctx.page, field).catch(() => []);
        if (options.length) field.options = options;
        else if (widget === "combobox") {
          // Nothing to choose from until you type: a suggestion box (e.g. a city search).
          field.kind = "text";
          field.hints = { ...field.hints, widget: "autocomplete" };
        }
      }
    }
    const mappings: FieldMapping[] = [];
    for (const field of fields) mappings.push(await ctx.resolveField(field));
    return { fields, mappings };
  }

  async fillFields(ctx: AdapterContext<Page>, mappings: FieldMapping[]): Promise<void> {
    for (const m of mappings) {
      if (m.mappedField.startsWith("documents.") || m.mappedField === "answer.library" || m.mappedField === "unknown") continue;
      await this.fillOne(ctx, m);
    }
  }

  async answerQuestions(ctx: AdapterContext<Page>, mappings: FieldMapping[]): Promise<void> {
    for (const m of mappings) {
      if (m.mappedField !== "answer.library" && m.mappedField !== "unknown") continue;
      await this.fillOne(ctx, m);
    }
  }

  async uploadDocuments(ctx: AdapterContext<Page>, documents: DocumentsToUpload, mappings: FieldMapping[]): Promise<void> {
    let uploaded = false;
    for (const m of mappings) {
      if (m.field.kind !== "file" || m.status === "SKIPPED") continue;
      const doc = m.mappedField === "documents.resume" ? documents.resume : m.mappedField === "documents.coverLetter" ? documents.coverLetter : undefined;
      if (!doc) continue;
      ctx.signal.throwIfAborted();
      const locator = await this.locate(ctx.page, m.field);
      await locator.setInputFiles(doc.path);
      uploaded = true;
      await ctx.log({ type: m.mappedField === "documents.resume" ? "RESUME_UPLOADED" : "COVER_LETTER_UPLOADED", message: `Uploaded ${doc.fileName} to "${m.detectedLabel}"` });
    }
    if (uploaded) await this.restoreAfterParsing(ctx, mappings);
  }

  async validate(ctx: AdapterContext<Page>): Promise<ValidationResult> {
    const native = (await ctx.page.evaluate(NATIVE_VALIDITY_SCRIPT)) as Array<{ label: string; message: string }>;
    const shown = (await ctx.page.evaluate(VALIDATION_SCRIPT)) as { errors: Array<{ label: string; message: string }>; alerts: string[] };
    const errors = [...native, ...shown.errors.filter((e) => !native.some((n) => n.label === e.label))];
    return { ok: errors.length === 0, errors };
  }

  async nextPage(ctx: AdapterContext<Page>): Promise<PageAdvance> {
    const button = await this.findButton(ctx.page, "next");
    if (!button) throw new AutomationError("SITE_CHANGED", "Couldn't find the button to the next page of the form");
    return this.clickAndWait(ctx, button);
  }

  async submit(ctx: AdapterContext<Page>): Promise<{ confirmation?: string } | { validation: ValidationResult }> {
    const button = await this.findButton(ctx.page, "submit");
    if (!button) throw new AutomationError("SITE_CHANGED", "Couldn't find the form's submit button");
    const result = await this.clickAndWait(ctx, button);
    const status = await this.getStatus(ctx);
    if (status.state === "submitted") return { confirmation: status.confirmation };
    if (status.state === "needs_human") throw new AutomationError(status.reason === "CAPTCHA" ? "CAPTCHA" : "AUTH_REQUIRED", status.detail);
    if (!result.moved) return { validation: result.validation };
    const validation = await this.validate(ctx);
    if (!validation.ok) return { validation };
    throw new AutomationError("SITE_CHANGED", "The form was sent but no confirmation appeared");
  }

  async getStatus(ctx: AdapterContext<Page>): Promise<AdapterStatus> {
    const { page } = ctx;
    const security = await this.security(page);
    const detail = { ...DEFAULT_HUMAN_DETAIL, ...this.options.humanDetail };
    if (security.captcha) return { state: "needs_human", reason: "CAPTCHA", detail: detail.CAPTCHA };
    if (security.mfa) return { state: "needs_human", reason: "MFA", detail: detail.MFA };
    if (security.login) return { state: "needs_human", reason: "AUTH_REQUIRED", detail: detail.AUTH_REQUIRED };
    const confirmation = (await page.evaluate(CONFIRMATION_SCRIPT)) as { confirmed: boolean; confirmation: string | null };
    const fields = await this.scan(page);
    if (confirmation.confirmed && fields.length === 0) return { state: "submitted", confirmation: confirmation.confirmation ?? undefined };
    const next = await this.findButton(page, "next");
    const submit = await this.findButton(page, "submit");
    const reviewPage = fields.length === 0 && !next && !!submit && (await this.isReviewPage(page));
    return { state: "in_progress", page: ctx.pageIndex, isFinalPage: !next && !!submit, hasForm: fields.length > 0 || reviewPage, humanSubmitOnly: security.scoreCheck };
  }

  async handleFailure(_ctx: AdapterContext<Page>, error: unknown): Promise<AdapterStatus> {
    const failure = classifyFailure(error);
    return { state: "failed", failure, message: error instanceof Error ? error.message.split("\n")[0]!.slice(0, 500) : String(error) };
  }

  // ─── hooks for platform adapters ──────────────────────────────────────────

  /**
   * A final "review your application" step with nothing to fill but a Submit
   * button. Platforms that have one say how to recognize it; elsewhere a page
   * without fields is something AutoApply can't handle.
   */
  protected async isReviewPage(_page: Page): Promise<boolean> {
    return false;
  }

  // ─── internals ────────────────────────────────────────────────────────────

  private async settle(page: Page) {
    await page.waitForLoadState("domcontentloaded");
    await page.waitForLoadState("networkidle", { timeout: 5000 }).catch(() => undefined);
  }

  private async scan(page: Page): Promise<ScannedField[]> {
    return (await page.evaluate(this.fieldsScript)) as ScannedField[];
  }

  private async security(page: Page) {
    return (await page.evaluate(SECURITY_SCRIPT)) as { captcha: boolean; mfa: boolean; login: boolean; signInText: boolean; scoreCheck: boolean };
  }

  /** Resolve a field to exactly one element, trying locator strategies in priority order. */
  private async locate(page: Page, field: DetectedField): Promise<Locator> {
    const tag = tagFor(field);
    for (const loc of field.locators) {
      let candidate: Locator;
      switch (loc.strategy) {
        case "label": candidate = page.getByLabel(loc.value, { exact: true }); break;
        case "name": candidate = page.locator(`${tag}[name=${cssString(loc.value)}]`); break;
        case "id": candidate = page.locator(`#${cssEscapeId(loc.value)}`); break;
        case "aria": candidate = page.locator(`[aria-label=${cssString(loc.value)}]`); break;
        case "dom": candidate = page.locator(loc.value); break;
      }
      if ((await candidate.count()) === 1) return candidate;
    }
    throw new AutomationError("SELECTOR_ERROR", `Couldn't find the "${field.label}" field on the page`);
  }

  /** The inputs of a radio or checkbox group, located by name, falling back to the DOM path. */
  private groupInputs(page: Page, field: DetectedField): Locator {
    const type = field.kind === "radio" ? "radio" : "checkbox";
    const name = field.hints?.name;
    if (name) return page.locator(`input[type="${type}"][name=${cssString(name)}]`);
    const dom = field.locators.find((l) => l.strategy === "dom");
    if (dom) return page.locator(dom.value);
    throw new AutomationError("SELECTOR_ERROR", `Couldn't find the "${field.label}" choices`);
  }

  private async pickInGroup(page: Page, field: DetectedField, wanted: string[], exclusive: boolean) {
    const type = field.kind === "radio" ? "radio" : "checkbox";
    const inputs = this.groupInputs(page, field);
    const options = field.options ?? [];
    const targets: Locator[] = [];
    for (const option of wanted) {
      const byLabel = inputs.and(page.getByRole(type, { name: option, exact: true }));
      if ((await byLabel.count()) === 1) {
        targets.push(byLabel);
        continue;
      }
      const value = field.optionValues?.[options.indexOf(option)];
      const byValue = value ? inputs.and(page.locator(`[value=${cssString(value)}]`)) : null;
      if (byValue && (await byValue.count()) === 1) targets.push(byValue);
      else throw new AutomationError("SELECTOR_ERROR", `Couldn't select "${option}" for "${field.label}"`);
    }
    if (!exclusive) {
      // Start from a clean group so the ticked boxes match the answer exactly.
      const count = await inputs.count();
      for (let i = 0; i < count; i++) if (await inputs.nth(i).isChecked()) await inputs.nth(i).uncheck();
    }
    for (const t of targets) await t.check();
  }

  /** Row of answer buttons (Yes / No): press the one with the answer's text. */
  private async pressAnswerButton(page: Page, field: DetectedField, value: string) {
    const container = await this.locate(page, field);
    const button = container.getByRole("button", { name: value, exact: true }).or(container.getByRole("radio", { name: value, exact: true }));
    if ((await button.count()) !== 1) throw new AutomationError("SELECTOR_ERROR", `Couldn't press "${value}" for "${field.label}"`);
    await button.click();
    const pressed = (await button.getAttribute("aria-pressed")) ?? (await button.getAttribute("aria-checked"));
    if (pressed === "false") throw new AutomationError("SELECTOR_ERROR", `"${value}" didn't stay selected for "${field.label}"`);
  }

  /** Open a custom dropdown, read its choices, and close it again without picking anything. */
  private async readOptions(page: Page, field: DetectedField): Promise<string[]> {
    const control = await this.locate(page, field);
    await control.click();
    await page.locator('[role="option"]').first().waitFor({ state: "visible", timeout: 1500 }).catch(() => undefined);
    const options = (await page.evaluate(OPEN_OPTIONS_SCRIPT)) as string[];
    await page.keyboard.press("Escape");
    await control.blur().catch(() => undefined);
    return [...new Set(options)];
  }

  /** The visible option with exactly this text, wherever the site renders its dropdown list. */
  private async visibleOption(page: Page, text: string): Promise<Locator> {
    const option = page.getByRole("option", { name: text, exact: true }).filter({ visible: true });
    await option.first().waitFor({ state: "visible", timeout: 3000 }).catch(() => undefined);
    return option;
  }

  private async pickCustomOption(page: Page, field: DetectedField, value: string) {
    const control = await this.locate(page, field);
    await control.click();
    if (field.hints?.widget === "combobox") await control.fill(value);
    const option = await this.visibleOption(page, value);
    if ((await option.count()) !== 1) {
      await page.keyboard.press("Escape");
      throw new AutomationError("SELECTOR_ERROR", `Couldn't choose "${value}" for "${field.label}"`);
    }
    await option.click();
  }

  /** Type into a suggestion box and pick the suggestion that matches the value; never an unrelated one. */
  private async typeAndSuggest(ctx: AdapterContext<Page>, field: DetectedField, value: string) {
    const { page } = ctx;
    const control = await this.locate(page, field);
    await control.click();
    await control.fill(value);
    await page.locator('[role="option"]').first().waitFor({ state: "visible", timeout: 3000 }).catch(() => undefined);
    const suggestions = (await page.evaluate(OPEN_OPTIONS_SCRIPT)) as string[];
    const match = chooseOption(value, suggestions);
    if (match && match.confidence >= 80) {
      await (await this.visibleOption(page, match.option)).first().click();
      return;
    }
    await page.keyboard.press("Escape");
    await ctx.log({ type: "NOTE", level: "WARNING", message: `"${field.label}" didn't suggest anything matching "${value}"; left as typed` });
  }

  private async fillOne(ctx: AdapterContext<Page>, m: FieldMapping): Promise<void> {
    if (m.value == null || m.status === "SKIPPED" || (m.status === "NEEDS_REVIEW" && m.source === "none")) return;
    ctx.signal.throwIfAborted();
    const { page } = ctx;
    const field = m.field;
    const widget = field.hints?.widget ?? "native";
    switch (field.kind) {
      case "radio":
        if (widget === "buttons") await this.pressAnswerButton(page, field, String(m.value));
        else await this.pickInGroup(page, field, [String(m.value)], true);
        return;
      case "checkbox":
        if (field.multiple) {
          await this.pickInGroup(page, field, Array.isArray(m.value) ? m.value : [m.value], false);
        } else {
          const locator = await this.locate(page, field);
          await locator.setChecked(m.value === "Yes");
        }
        return;
      case "select": {
        if (widget === "combobox" || widget === "listbox") {
          await this.pickCustomOption(page, field, String(m.value));
          return;
        }
        const locator = await this.locate(page, field);
        await locator.selectOption({ label: String(m.value) });
        return;
      }
      case "file":
        return;
      default: {
        const value = Array.isArray(m.value) ? m.value.join(", ") : m.value;
        if (widget === "autocomplete") {
          await this.typeAndSuggest(ctx, field, value);
          return;
        }
        const locator = await this.locate(page, field);
        await locator.fill(value);
        // Some sites reformat or reject input; read it back so a silent mismatch is caught by validation.
        const actual = await locator.inputValue();
        if (actual.replace(/\D/g, "") !== value.replace(/\D/g, "") && actual.trim() !== value.trim() && field.kind !== "date") {
          await ctx.log({ type: "NOTE", level: "WARNING", message: `"${field.label}" shows "${actual.slice(0, 80)}" after filling` });
        }
      }
    }
  }

  /**
   * Many ATSs read an uploaded resume and overwrite the fields with what they
   * parsed. The Master Profile is the source of truth: put its values back,
   * and empty the fields AutoApply deliberately left blank, so nothing is sent
   * that the profile doesn't say.
   */
  private async restoreAfterParsing(ctx: AdapterContext<Page>, mappings: FieldMapping[]) {
    const { page } = ctx;
    await page.waitForLoadState("networkidle", { timeout: 5000 }).catch(() => undefined);
    if (this.options.uploadSettleMs) await page.waitForTimeout(this.options.uploadSettleMs);
    const restored: string[] = [];
    const cleared: string[] = [];
    for (const m of mappings) {
      const typed = ["text", "textarea", "email", "phone", "url", "number"].includes(m.field.kind) && (m.field.hints?.widget ?? "native") === "native";
      if (!typed || Array.isArray(m.value)) continue;
      const wanted = m.status === "ANSWERED" && m.value != null ? m.value : m.status === "SKIPPED" ? "" : null;
      if (wanted == null) continue;
      const locator = await this.locate(page, m.field).catch(() => null);
      if (!locator) continue;
      const actual = await locator.inputValue().catch(() => wanted);
      if (actual.trim() === wanted.trim()) continue;
      await locator.fill(wanted);
      (wanted ? restored : cleared).push(displayLabel(m.detectedLabel));
    }
    const list = (labels: string[]) => labels.slice(0, 3).map((l) => `"${l}"`).join(", ");
    if (restored.length) await ctx.log({ type: "NOTE", message: `The site rewrote ${restored.length} field${restored.length === 1 ? "" : "s"} from your resume (${list(restored)}); restored them from your Master Profile` });
    if (cleared.length) await ctx.log({ type: "NOTE", message: `The site filled ${cleared.length} field${cleared.length === 1 ? "" : "s"} from your resume that your profile doesn't cover (${list(cleared)}); cleared ${cleared.length === 1 ? "it" : "them"}` });
  }

  private async findStartButton(page: Page): Promise<Locator | null> {
    for (const selector of this.options.startButtons ?? []) {
      const candidate = page.locator(selector).filter({ visible: true });
      if ((await candidate.count()) === 1 && !NEVER_PRESS.test(clean((await candidate.textContent()) ?? ""))) return candidate;
    }
    const start = page.getByRole("link", { name: START }).or(page.getByRole("button", { name: START })).filter({ visible: true });
    const count = await start.count();
    for (let i = 0; i < count; i++) {
      const candidate = start.nth(i);
      if (!NEVER_PRESS.test(clean((await candidate.textContent()) ?? ""))) return candidate;
    }
    return null;
  }

  private async findButton(page: Page, kind: "next" | "submit"): Promise<Locator | null> {
    // The platform's own navigation buttons first, classified by what they say.
    for (const selector of this.options.navigationButtons ?? []) {
      const candidate = page.locator(selector).filter({ visible: true });
      if ((await candidate.count()) !== 1 || !(await candidate.isEnabled())) continue;
      const text = clean((await candidate.getAttribute("aria-label")) || (await candidate.textContent()) || "");
      const isSubmit = SUBMIT.test(text) && !NEXT.test(text);
      if (kind === "submit" ? isSubmit : NEXT.test(text)) return candidate;
    }
    const buttons = ((await page.evaluate(this.navScript)) as ScannedButton[]).filter((b) => !NEVER_PRESS.test(b.text));
    const pattern = kind === "next" ? NEXT : SUBMIT;
    let match = buttons.find((b) => pattern.test(b.text));
    if (!match && kind === "submit" && !buttons.some((b) => NEXT.test(b.text))) {
      // A form with a single unlabeled submit button.
      const formSubmits = buttons.filter((b) => b.inForm && b.type === "submit");
      if (formSubmits.length === 1) match = formSubmits[0];
    }
    if (!match) return null;
    const byRole = page.getByRole("button", { name: match.text, exact: true });
    if (match.text && (await byRole.count()) === 1) return byRole;
    const byPath = page.locator(match.domPath);
    return (await byPath.count()) === 1 ? byPath : null;
  }

  private async fieldSignature(page: Page) {
    return JSON.stringify((await this.scan(page)).map((f) => f.name + f.label));
  }

  /** Click a navigation button and wait for either a new page or visible validation errors. */
  private async clickAndWait(ctx: AdapterContext<Page>, button: Locator): Promise<PageAdvance> {
    const { page } = ctx;
    ctx.signal.throwIfAborted();
    const before = { url: page.url(), fields: await this.fieldSignature(page), text: await this.pageText(page) };
    const navigation = page.waitForNavigation({ timeout: 15_000, waitUntil: "domcontentloaded" }).then(() => true).catch(() => false);
    await button.click();
    const navigated = await Promise.race([navigation, page.waitForTimeout(2500).then(() => false)]);
    if (!navigated) await page.waitForLoadState("domcontentloaded").catch(() => undefined);
    await page.waitForLoadState("networkidle", { timeout: 5000 }).catch(() => undefined);
    const after = { url: page.url(), fields: await this.fieldSignature(page), text: await this.pageText(page) };
    if (after.url !== before.url || after.fields !== before.fields) {
      const validation = await this.validate(ctx);
      // Same page re-rendered with errors (server-side validation).
      if (after.url === before.url && !validation.ok) return { moved: false, validation };
      return { moved: true };
    }
    const validation = await this.validate(ctx);
    if (validation.ok) {
      // A single-page app may swap in a confirmation or a review step without changing the URL or the fields.
      if (after.text !== before.text) {
        const confirmation = (await page.evaluate(CONFIRMATION_SCRIPT)) as { confirmed: boolean };
        if (confirmation.confirmed || (await this.isReviewPage(page))) return { moved: true };
      }
      const shown = (await page.evaluate(VALIDATION_SCRIPT)) as { alerts: string[] };
      return { moved: false, validation: { ok: false, errors: shown.alerts.length ? shown.alerts.map((a) => ({ label: "Form", message: a })) : [{ label: "Form", message: "The page didn't change after clicking the button" }] } };
    }
    return { moved: false, validation };
  }

  private async pageText(page: Page): Promise<string> {
    return ((await page.evaluate("document.body ? document.body.innerText.slice(0, 5000) : ''").catch(() => "")) as string) ?? "";
  }
}

function cssEscapeId(id: string): string {
  return id.replace(/([^a-zA-Z0-9_-])/g, "\\$1");
}
